### ISSUE TITLE
Inconsistencies of scripts.

### ISSUE THREAD

**Issue by Valien** [awslabs/efs-backup#6]
I'm seeing inconsistencies of running this. Some days it will run fine but some days I get weird errors like the following:

`    "Message": "The SSM script could not update the DynamoDB table with backup status, please check the logs in the S3 bucket for the details.",`

Checked logs but they are not really providing a ton of information. It will run like this for a few days and still transfer files and then will backup fine w/o any issues.

Backing up about 20 GB of data right now.

**Comment by gsingh04** [comment]
Please check the ssm-logs, to identify the issue. We have identified issue where backups are successful yet the customer receives this notification due to failure to fetch certain CloudWatch metrics. Your case shows similar symptoms. Would you be able to dive into ssm-logs and look for CloudWatch related errors.
solution logging details: https://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/appendix-b.html

**Comment by Valien** [comment]
Here's my stdout from last night:

> 
>
> 2018-02-05T05:45:45 -- uploading cloud init logs
>Completed 63.8 KiB/63.8 KiB (1.2 MiB/s) with 1 file(s) remaining
upload: var/log/cloud-init-output.log to s3://<redacted>-efs-backup-efslogbucket-1m3yhuaiokdqw/ec2-logs/<redacted>-efs-backup-backup-20180205-0545.log
-- 2018-02-05T05:45:46 -- upload ec2 cloud init logs to S3, status: 0
-- 2018-02-05T05:45:46 -- uploading backup (fpsync) logs
-- 2018-02-05T05:45:46 -- upload backup fpsync logs to S3 status: 0
-- 2018-02-05T05:45:46 -- fpsync foreground process-id: 
-- 2018-02-05T05:45:46 -- kill fpsync pid status: 0
-- 2018-02-05T05:45:46 -- /tmp/efs-fpsync.log file does not exist
-- 2018-02-05T05:45:46 -- Number of files: 
-- 2018-02-05T05:45:46 -- Number of files transferred: 
-- 2018-02-05T05:45:46 -- Total file size: 
-- 2018-02-05T05:45:46 -- Total transferred file size: 
rsync_delete_start:2018-02-05T05:45:46
-- 2018-02-05T05:45:46 -- sudo rsync -r --delete --existing --ignore-existing --ignore-errors --log-file=/tmp/efs-backup-rsync.log  /backup/ /mnt/backups/<redacted>-efs-backup/daily.0/
rsync delete status: 0
rsync_delete_stop:2018-02-05T06:20:47
-- 2018-02-05T06:20:47 -- sudo touch /mnt/backups/<redacted>-efs-backup/daily.0/
-- 2018-02-05T06:20:47 -- backup finish time: 2018-02-05T06:20:47
-- 2018-02-05T06:20:47 -- uploading backup (rsync delete) logs
Completed 141 Bytes/141 Bytes (1.2 KiB/s) with 1 file(s) remaining
upload: tmp/efs-backup-rsync.log to s3://<redacted>-efs-backup-efslogbucket-1m3yhuaiokdqw/efs-backup-logs/<redacted>-efs-backup-backup-rsync-delete-20180205-0620.log
-- 2018-02-05T06:20:48 -- upload rsync delete logs to S3 status: 0
-- 2018-02-05T06:20:48 -- source efs BurstCreditBalance after backup: 2.30897441833e+12
-- 2018-02-05T06:20:48 -- backup incomplete (id: a4f496b5)
-- 2018-02-05T06:20:48 -- dynamo db update status: 0
-- 2018-02-05T06:20:48 -- updating lifecycle hook
-- 2018-02-05T06:20:49 -- lifecycle hook update status: 0

and the stderr:

> 
> 
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100    10  100    10    0     0  25706      0 --:--:-- --:--:-- --:--:-- 10000
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100    19  100    19    0     0  57575      0 --:--:-- --:--:-- --:--:-- 19000
> 
> The user-provided path /tmp/efs-backup.log does not exist.
> head: cannot open '/tmp/efs-fpsync.log' for reading: No such file or directory
> 
> Usage:
>  kill [options] <pid|name> [...]
> 
> Options:
>  -a, --all              do not restrict the name-to-pid conversion to processes
>                         with the same uid as the present process
>  -s, --signal <sig>     send specified signal
>  -q, --queue <sig>      use sigqueue(2) rather than kill(2)
>  -p, --pid              print pids without signaling them
>  -l, --list [=<signal>] list signal names, or convert one to a name
>  -L, --table            list signal names and numbers
> 
>  -h, --help     display this help and exit
>  -V, --version  output version information and exit
> 
> For more details see kill(1).
> cat: /tmp/efs-backup.log: No such file or directory
> cat: /tmp/efs-backup.log: No such file or directory
> cat: /tmp/efs-backup.log: No such file or directory
> cat: /tmp/efs-backup.log: No such file or directory
> 
> An error occurred (ValidationException) when calling the UpdateItem operation:  >ExpressionAttributeValues contains invalid value: The parameter cannot be converted to a numeric > value for key :f1
> 

Weird thing is that this is inconsistent. I have a 7 day rotation and 3-4 days will be fine/successfull then 2-3 days like this. Same error logs in ssm-logs. 

I removed the pertinent client info hence the <redacted> portions.

**Comment by gsingh04** [comment]
looking from the logs, seems like efs-backup.log and efs-fpsync.log did not exist. this would have happened if the backup process did not run (at this point not sure why) 

_check here:_ https://github.com/awslabs/efs-backup/blob/e12ff50cb3f2569ce87ae9648eb3d4e8e53aefe8/source/scripts/efs-backup-fpsync.sh#L125

There are essentially 3 logs
/ec2-logs
/ssm-logs
/efs-backup-logs

Can you also look at relevant ec2-logs for the same backup to dive further into this issue.

**Comment by Valien** [comment]
Here is the rsync delete log from same time event (2/5/18) of the above logs:

**efs-backup-logs**

> 2018/02/05 05:45:46 [14540] building file list
>2018/02/05 06:20:47 [14540] sent 6909993 bytes  received 220918 bytes  total size 38133977784

Noticed that there are no backup-fpsync logs files for last night due to the error it seems.

**ec2-logs**

All build parts removed as those went fine. Here is the tail of the logs from the same date:

>make[1]: Leaving directory `/fpart-fpart-0.9.3'
>-- 2018-02-05T02:01:47 -- sudo mkdir /backup
>-- 2018-02-05T02:01:47 -- sudo mkdir /mnt/backups
>-- 2018-02-05T02:01:47 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 10.0.132.45:/ /backup
-- 2018-02-05T02:01:47 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 10.0.130.250:/ /mnt/backups
remove_snapshot_start:2018-02-05T02:01:47
-- 2018-02-05T02:01:47 -- sudo rm -rf /mnt/backups/client-redacted-efs-backup/daily.6
remove_snapshot_stop:2018-02-05T03:34:12
-- 2018-02-05T03:34:12 -- sudo mv /mnt/backups/client-redacted-efs-backup/daily.5 /mnt/backups/client-redacted-efs-backup/daily.6
-- 2018-02-05T03:34:12 -- sudo mv /mnt/backups/client-redacted-efs-backup/daily.4 /mnt/backups/client-redacted-efs-backup/daily.5
-- 2018-02-05T03:34:12 -- sudo mv /mnt/backups/client-redacted-efs-backup/daily.3 /mnt/backups/client-redacted-efs-backup/daily.4
-- 2018-02-05T03:34:12 -- sudo mv /mnt/backups/client-redacted-efs-backup/daily.2 /mnt/backups/client-redacted-efs-backup/daily.3
-- 2018-02-05T03:34:12 -- sudo mv /mnt/backups/client-redacted-efs-backup/daily.1 /mnt/backups/client-redacted-efs-backup/daily.2
create_snapshot_start:2018-02-05T03:34:12
-- 2018-02-05T03:34:12 --  sudo cp -al /mnt/backups/client-redacted-efs-backup/daily.0 /mnt/backups/client-redacted-efs-backup/daily.1

And noticed in the Dynamo DB table there is not success/failure key written.

**Comment by waydeg** [comment]
I am having the same issue. The message is due to the fact that the DDB table is not being updated with the Backup Status, so there is no BackupStatus attribute in the table.  Here is the output from the ssm log:

-- 2018-02-03T04:46:45 -- uploading cloud init logs
Completed 62.6 KiB/62.6 KiB (849.3 KiB/s) with 1 file(s) remaining
upload: var/log/cloud-init-output.log to s3://efs-backup-efslogbucket-6y6mi46t4reh/ec2-logs/efs-backup-backup-20180203-0446.log
-- 2018-02-03T04:46:46 -- upload ec2 cloud init logs to S3, status: 0
-- 2018-02-03T04:46:46 -- uploading backup (fpsync) logs
-- 2018-02-03T04:46:46 -- upload backup fpsync logs to S3 status: 0
-- 2018-02-03T04:46:46 -- fpsync foreground process-id: 
-- 2018-02-03T04:46:46 -- kill fpsync pid status: 0
-- 2018-02-03T04:46:46 -- /tmp/efs-fpsync.log file does not exist
-- 2018-02-03T04:46:46 -- Number of files: 
-- 2018-02-03T04:46:46 -- Number of files transferred: 
-- 2018-02-03T04:46:46 -- Total file size: 
-- 2018-02-03T04:46:46 -- Total transferred file size: 
rsync_delete_start:2018-02-03T04:46:46
-- 2018-02-03T04:46:46 -- sudo rsync -r --delete --existing --ignore-existing --ignore-errors --log-file=/tmp/efs-backup-rsync.log  /backup/ /mnt/backups/efs-backup/daily.0/

**Comment by cguillerminet** [comment]
Same issue here, I can confirm the dynamodb table is not updated, BackupStatus, BackupStopTime and CreateHardlinks fields were set for the first backup, then for next ones they always remain empty.

**Comment by gsingh04** [comment]
in the logs I can see following message:
`/tmp/efs-fpsync.log file does not exist`

would you guys be able to pull the related EC2 logs and identify if you see logging like this:

> -- 2018-02-07T02:02:16 -- sudo mkdir /backup
> -- 2018-02-07T02:02:16 -- sudo mkdir /mnt/backups
> -- 2018-02-07T02:02:16 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 10.51.1.170:/ /backup
> -- 2018-02-07T02:02:16 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 10.51.1.117:/ /mnt/backups
> remove_snapshot_start:2018-02-07T02:02:16
> -- 2018-02-07T02:02:16 -- sudo rm -rf /mnt/backups/efs-backup/daily.6
> remove_snapshot_stop:2018-02-07T20:14:46
> -- 2018-02-07T20:14:46 -- sudo mv /mnt/backups/efs-backup/daily.5 /mnt/backups/efs-backup/daily.6
> -- 2018-02-07T20:14:46 -- sudo mv /mnt/backups/efs-backup/daily.4 /mnt/backups/efs-backup/daily.5
> -- 2018-02-07T20:14:46 -- sudo mv /mnt/backups/efs-backup/daily.3 /mnt/backups/efs-backup/daily.4
> -- 2018-02-07T20:14:46 -- sudo mv /mnt/backups/efs-backup/daily.2 /mnt/backups/efs-backup/daily.3
> -- 2018-02-07T20:14:46 -- sudo mv /mnt/backups/efs-backup/daily.1 /mnt/backups/efs-backup/daily.2
> create_snapshot_start:2018-02-07T20:14:46
> -- 2018-02-07T20:14:46 --  sudo cp -al /mnt/backups/efs-backup/daily.0 /mnt/backups/efs-backup/daily.1
> create_snapshot_stop:2018-02-09T05:38:38
> -- 2018-02-09T05:38:38 --  sudo rm /tmp/efs-backup.log
> rm: cannot remove ‘/tmp/efs-backup.log’: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100     9  100     9    0     0   7456      0 --:--:-- --:--:-- --:--:--  9000
> Stating backup.....
> -- 2018-02-09T05:38:38 --  sudo "PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin" /usr/local/bin/fpsync -n 16 -o "-a --stats --numeric-ids --log-file=/tmp/efs-backup.log" /backup/ /mnt/backups/efs-backup/daily.0/
> which: no mail in (/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin)
> -- 2018-02-09T10:36:17 -- Backup script finished before the backup window, stopping the ec2 instance.
> 

In the above logging you can see `Stating backup.....` this will help us identify if the backup actually ran. The error message identified above makes me believe the backup did not run.

**Comment by waydeg** [comment]
My log doesn't reach that point.  Here is the end of it:
-- 2018-02-19T02:02:41 -- sudo mkdir /backup
-- 2018-02-19T02:02:41 -- sudo mkdir /mnt/backups
-- 2018-02-19T02:02:41 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 192.168.3.186:/ /backup
-- 2018-02-19T02:02:42 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 192.168.2.52:/ /mnt/backups
remove_snapshot_start:2018-02-19T02:02:42
-- 2018-02-19T02:02:42 -- sudo rm -rf /mnt/backups/efs-backup/daily.6
remove_snapshot_stop:2018-02-19T05:08:55
-- 2018-02-19T05:08:55 -- sudo mv /mnt/backups/efs-backup/daily.5 /mnt/backups/efs-backup/daily.6
-- 2018-02-19T05:08:55 -- sudo mv /mnt/backups/efs-backup/daily.4 /mnt/backups/efs-backup/daily.5
-- 2018-02-19T05:08:55 -- sudo mv /mnt/backups/efs-backup/daily.3 /mnt/backups/efs-backup/daily.4
-- 2018-02-19T05:08:55 -- sudo mv /mnt/backups/efs-backup/daily.2 /mnt/backups/efs-backup/daily.3
-- 2018-02-19T05:08:55 -- sudo mv /mnt/backups/efs-backup/daily.1 /mnt/backups/efs-backup/daily.2
create_snapshot_start:2018-02-19T05:08:55
-- 2018-02-19T05:08:55 --  sudo cp -al /mnt/backups/efs-backup/daily.0 /mnt/backups/efs-backup/daily.1

**Comment by gsingh04** [comment]
@waydeg looks like your backup activity got stuck at cp -al step.
`-- 2018-02-19T05:08:55 -- sudo cp -al /mnt/backups/efs-backup/daily.0 /mnt/backups/efs-backup/daily.1`
We create hardlinks in this step. This step would not kick in on the initial backup, however it would be performed on subsequent backups so you can restore to a particular snapshot. I would recommend performing a POC with a smaller data set or increasing the backup window.

**Comment by waydeg** [comment]
I had already increased the backup window to 6 hours and I tried some smaller datasets. What is the practical size limit for a backup with this approach?

**Comment by waydeg** [comment]
The total size of my EFS is 200 GB.  But, I have divided the backups into four pieces by subfolders, so they shouldn’t be larger than 50GB.  But. they are all failing.

**Comment by cguillerminet** [comment]
In my case I do reach that point:

> make[2]: Entering directory `/fpart-fpart-0.9.3'
> make[2]: Nothing to be done for `install-exec-am'.
> make[2]: Nothing to be done for `install-data-am'.
> make[2]: Leaving directory `/fpart-fpart-0.9.3'
> make[1]: Leaving directory `/fpart-fpart-0.9.3'
> -- 2018-02-19T01:02:35 -- sudo mkdir /backup
> -- 2018-02-19T01:02:35 -- sudo mkdir /mnt/backups
> -- 2018-02-19T01:02:35 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 10.0.51.146:/ /backup
> -- 2018-02-19T01:02:35 -- sudo mount -t nfs -o nfsvers=4.1 -o rsize=1048576 -o wsize=1048576 -o timeo=600 -o retrans=2 -o hard 10.0.51.243:/ /mnt/backups
> remove_snapshot_start:2018-02-19T01:02:35
> remove_snapshot_stop:2018-02-19T01:02:35
> -- 2018-02-19T01:02:36 -- sudo mv /mnt/backups/efs-backup/daily.3 /mnt/backups/efs-backup/daily.4
> -- 2018-02-19T01:02:36 -- sudo mv /mnt/backups/efs-backup/daily.2 /mnt/backups/efs-backup/daily.3
> -- 2018-02-19T01:02:36 -- sudo mv /mnt/backups/efs-backup/daily.1 /mnt/backups/efs-backup/daily.2
> create_snapshot_start:2018-02-19T01:02:36
> -- 2018-02-19T01:02:36 --  sudo cp -al /mnt/backups/efs-backup/daily.0 /mnt/backups/efs-backup/daily.1
> create_snapshot_stop:2018-02-19T09:34:17
> -- 2018-02-19T09:34:17 --  sudo rm /tmp/efs-backup.log
> rm: cannot remove ‘/tmp/efs-backup.log’: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100     9  100     9    0     0  13138      0 --:--:-- --:--:-- --:--:--  9000
> Stating backup.....
> -- 2018-02-19T09:34:17 --  sudo "PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin" /usr/local/bin/fpsync -n 13 -o "-a --stats --numeric-ids --log-file=/tmp/efs-backup.log" /backup/ /mnt/backups/efs-backup/daily.0/
> which: no mail in (/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin)
> -- 2018-02-19T10:06:42 -- Backup script finished before the backup window, stopping the ec2 instance.
> ci-info: no authorized ssh keys fingerprints found for user ec2-user.
> Cloud-init v. 0.7.6 finished at Mon, 19 Feb 2018 10:06:43 +0000. Datasource DataSourceEc2.  Up 32728.26 seconds

My backup window is 20 hours for 1.1 TB. Anyway, th e script  says it finishes before the backup window so everything should be ok.

**Comment by Valien** [comment]
Glad to know I'm not the only one seeing these issues. Hope someone can help figure out what is going on. I've pored over the logs and everything and can't seem to find anything amiss.

**Comment by Valien** [comment]
Quick update: Haven't changed any processes and backup still fails 3-4 times a week but then will run fine 2-3 times a week. Same errors, same log info, etc. Might delete everything and start over and see if data has been corrupted hence causing the errors.

**Comment by yazzzuk** [comment]
Seeing the exact same issue with one of our customers. Backups have been completing for the past few days after failing for a while. Odd thing is, no new logs have been written to "efs-backup-logs" since 19th February, even though backups have intermittently worked since then. The last entry on the 19th was:

2018-02-19T03:52:57 --  sudo cp -al /mnt/backups/efs-backup/daily.0 /mnt/backups/efs-backup/daily.1

We have a Support ticket open for this.

**Comment by HitkoDev** [comment]
I'm experiencing the same problems, and one thing I've noticed is when this happens, backup instance syslog shows an error while executing this line https://github.com/awslabs/efs-backup/blob/917d5c2ced6b672a69e8df7d8f29b53cdf3e2506/deployment/efs-to-efs-backup.template#L266

```
Cannot find a valid baseurl for repo: amzn-main/latest
Could not retrieve mirrorlist http://repo.eu-central-1.amazonaws.com/latest/main/mirror.list error was
12: Timeout on http://repo.eu-central-1.amazonaws.com/latest/main/mirror.list: (28, 'Connection timed out after 5001 milliseconds')
```

I presume SSM agent fails to install, and that leads to script being unable to update data in the database.

**Comment by yazzzuk** [comment]
We got this working in the end working with AWS Support. Backups were taking place it seemed, but the status wasn't being reported correctly. The reason was because while backing up an active filesystem, if some files are removed before they're transferred (EFS backups do not take snapshots and quiesce the filesytem), rsync reports a warning in the last line of the /tmp/efs-fpsync.log - the ssm.sh script checks the last line for a particular status to determine the status of the backup and update the relevant table in DynamoDB.

The workaround was to change `tail -n 2 /tmp/efs-fpsync.log | grep -Po '\d+(?=%)` in lines 42 and 49 in ssm.sh, to `cat /tmp/efs-fpsync.log | grep -Po '\d+(?=%)`. 

Also keep in mind if you have a number of EFS volumes, a backup instance is spawned per volume as per the ASG so you may run into instance limits unless you've asked for an increase or staggered your backups.

AWS are going to make enhancements to the backup script including more efficient clean ups post-backup.

**Comment by gsingh04** [comment]
@HitkoDev latest Amazon Linux AMIs are fetched in the solution. All of them come pre-installed with the SSM agent. Failure to install agent has no impact on the solution. Solution was released when SSM agent did not come pre-packed hence the step. [ref link](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html#agent-install-al)

**Comment by HitkoDev** [comment]
@gsingh04 then how do you explain the line I quoted, which clearly tries (and sometimes fails) to install SSM agent on the EC2 instance?

**Comment by gsingh04** [comment]
@HitkoDev the subnet that you chose for the deployment must have **outbound** internet reachability, which could be either through internet gateway or nat-gateway. Please make sure you fulfill the pre-reqs mentioned [here](https://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/deployment.html). Alternate VPC configuration needed for the solution to work [here](https://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/appendix-c.html).

**Comment by HitkoDev** [comment]
Please read my comment again, would you? I'm experiencing the behaviour stated in this issue (i.e. some days backup works fine, while other days it gives unknown status, while files seem to be backed up just fine).

Clearly gateway isn't a problem, otherwise the script would fail every time, not just on random days.

**Comment by rwhirn** [comment]
@HitkoDev I would guess that the script tries to "get" ssm agent every time and when it does, then it says "already installed - don't need it" but in the case where for whatever reason it can't "get" ssm, it fails before getting to the point where it realizes "oh, I don't need it"

**Comment by rwhirn** [comment]
@gsingh04 I experience the same problem. Backup worked on May8, not on May9, worked May 10, 11, 12, 13, 14, not on May 15, worked May16, not on May17, 18, 19.

However - I have NO logs in s3 on the days it didn't work. No ec2-logs, no efs-backup-logs, no ssm-logs. They only appear on the days the backup runs successfully.

I do have cloudwatch logs which shows it started then 3 hours later terminated (I assume from timeout).

My backup is pretty tiny, takes 9 minutes to delete the week old backup, 10 minutes to copy yesterday's backup to today, then 3 minutes to sync up a couple hundred files on the days it works.

**Comment by rwhirn** [comment]
@gsingh04 Failed again. I have attached the system log to show all the things that are failing in the EC2 instance startup.
[aws-error.txt](https://github.com/awslabs/efs-backup/files/2042924/aws-error.txt)
Relevant portions:
Starting cloud-init: Cloud-init v. 0.7.6 running 'modules:config' at Sun, 27 May 2018 08:01:35 +0000. Up 6.08 seconds.
Loaded plugins: priorities, update-motd, upgrade-helper

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
Cannot find a valid baseurl for repo: amzn-main/latest
Could not retrieve mirrorlist http://repo.us-east-1.amazonaws.com/latest/main/mirror.list error was
12: Timeout on http://repo.us-east-1.amazonaws.com/latest/main/mirror.list: (28, 'Connection timed out after 5001 milliseconds')
May 27 08:01:51 cloud-init[2528]: util.py[WARNING]: Package upgrade failed
May 27 08:01:51 cloud-init[2528]: cc_package_update_upgrade_install.py[WARNING]: 1 failed with exceptions, re-raising the last one
May 27 08:01:51 cloud-init[2528]: util.py[WARNING]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) failed
Generating SSH2 ED25519 host key: [  OK  ]
Starting sshd: [  OK  ]
Starting ntpd: [  OK  ]
Starting sendmail: [  OK  ]
Starting sm-client: [  OK  ]
Starting crond: [  OK  ]
Starting atd: [  OK  ]
Starting cloud-init: Cloud-init v. 0.7.6 running 'modules:final' at Sun, 27 May 2018 08:01:51 +0000. Up 22.12 seconds.
Loaded plugins: priorities, update-motd, upgrade-helper

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
Cannot find a valid baseurl for repo: amzn-main/latest
Could not retrieve mirrorlist http://repo.us-east-1.amazonaws.com/latest/main/mirror.list error was
12: Timeout on http://repo.us-east-1.amazonaws.com/latest/main/mirror.list: (28, 'Connection timed out after 5001 milliseconds')
start: Job is already running: amazon-ssm-agent
--2018-05-27 08:02:07--  https://s3.amazonaws.com/solutions-reference/efs-backup/latest/efs-ec2-backup.sh
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.224.155
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.224.155|:443... failed: Connection timed out.
Retrying.

**Comment by gsingh04** [comment]
@rwhirn can you confirm if you experience this intermittent issue only in us-east-1 or in other regions too? Also, would you be able to share instance-id of one of the instances which failed?

**Comment by jclynny** [comment]
I am getting email failures about backup, rather "Incomplete" EFS backups, but when looking into the underlying logs (stdout) I'm seeing that the rsync finished and backup completed successfully.  It would be swell if this could get addressed as the solution right now is not giving folks on my side much confidence that backups are occurring as expected.  I've had a case open with AWS Support and all logs have been examined and they feel it's related to the underlying ssm script returning back a failure before the rsync process starts.  Since I don't see this explicitly in this thread, is anyone aware of this issue and do you view it to be related to this Git Issue like AWS Support does?

**Comment by gsingh04** [comment]
@jclynny we are aware of an issue where we calculate parts done/backup percentage from last 2 lines of efs-fpsync.log
https://github.com/awslabs/efs-backup/blob/48dcac2197f8bd48d20c68cf4673606b5a2d44d9/source/lib/ssm.sh#L56
The script should not expect the status is on the 2nd last line ("tail -n 2") This is creating undesired behavior of receiving 'Incomplete' notification even in case where backup completed. To fix this at your end you may try: 
`_backup_percentage=$(cat /tmp/efs-fpsync.log | grep -Po '\d+(?=%)')`
We are conducting few tests at our end, in the meanwhile let us know if this helps.

**Comment by rwhirn** [comment]
@gsingh04 I am only using us-east-1 at this time. Regarding a failed instance - as a matter of fact, last night's backup has failed and the instance is still alive for the next 2 hours or so. It is i-010845f9289542a1f

**Comment by rwhirn** [comment]
garvit:

I am only using us-east-1 at this time. Regarding a failed instance - as a matter of fact, last night's backup has failed and the instance is still alive for the next 2 hours or so. It is i-010845f9289542a1f

Monday, May 28, 2018, 9:06:46 PM, you wrote:


@rwhirn can you confirm if you experience this intermittent issue only in us-east-1 or in other regions too? Also, would you be able to share instance-id of one of the instances which failed?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


RWH
--
----------------------------------------------------------------
Robert W. Hirn
National Health Delivery Systems, Inc.
Custom Software Design for the Healthcare Industry Since 1972
mailto:rwh@nhds.net
Phone: +1-312/642-4655  FAX: +1-312/337-9908

**Comment by gsingh04** [comment]
@rwhirn I checked your instance at my end. It is in a private subnet(subnet-a3c9df8f), with no outbound internet access(rtb-7765ba0d). Please make sure your chosen subnets as part of EFS Backup deployment allow outbound internet access. It might be the case where you have chosen 1 public and 1 private subnet as part of the deployment, which would explain why it succeeds and fails intermittently.

**Comment by rwhirn** [comment]
@gsingh04 I'm **so** stupid.

Anyway, did you see this in the CF template:

> Cannot render the template because of an error.: YAMLException: duplicated mapping key at line 380, column 49: ... !Sub ${EFSBackupStartEvent.Arn} ^

`
  BackupStartEventLambdaPermission:

    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub ${Orchestrator}
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !Sub ${EFSBackupStartEvent.Arn}
      SourceArn: !Sub ${EFSBackupStartEvent.Arn}`

**Comment by gsingh04** [comment]
@rwhirn this should be fixed now

**Comment by jclynny** [comment]
@gsingh04 Is there any action needed on the customer's end to "update" to get this issue fixed?  I presume no, but I'm still getting about a 50% fail rate on nightly backups.  I'm seeing some "succeed" and still some that say "Incomplete".  Thoughts?

**Comment by gsingh04** [comment]
we are in the process of releasing efs backup v1.3, please standby for further updates. we have addressed above mentioned issues in upcoming release.

**Comment by gsingh04** [comment]
we have released efs-backup v1.3, please feel free to update here with further concerns 
https://aws.amazon.com/answers/infrastructure-management/efs-backup/

**Comment by Valien** [comment]
thanks @gsingh04! I went ahead and created a new stack set with the updated scripts and will monitor it over next few days to see how it runs. Going to run this alongside the current iteration and see if any errors pop up!

**Comment by yazzzuk** [comment]
@gsingh04 - the script still only creates two mount targets for backup volumes. Most regions have three AZs so this causes a failure if the backup node spins up in an AZ that's not defined in one of the two mount targets the script creates. The third mount target needs to be created manually or the script needs updating before use. Easily fixable post-deployment, but didn't see anything in the documentation about it.

**Comment by gsingh04** [comment]
@yazzzuk we covered this under [prerequisites.](https://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/deployment.html) We ask customers to provide 2 subnets during efs-to-efs-backup.template deployment. These 2 subnets should be in 2 AZs where source EFS has mount targets. The deployment creates mount targets for the backup EFS in the same 2 subnets/AZs. As such it is not possible for the backup node to spin up in an AZ different from the backup volume mount targets as the same subnets/AZs are getting used with the EFS and the AutoScaling Group.

**Comment by Valien** [comment]
Just wanted to comment on the update:

Works great! Been running it now for a solid week and 0 errors. Backing up all my data within the timeframe and using same settings as I had previously. 

Thanks for the fix! Going to close the issue now!

**Comment by gsingh04** [comment]
Thanks for the feedback.

**Comment by Resisty** [comment]
Hello,

I had deployed this solution last week (2018-08-09) and it initially ran successfully, but now reports incomplete backups:
```
{
    "BackupId": "9d74c8a7",
    "BackupPrefix": "/",
    "BackupStartTime": "2018-08-13T16:08:17",
    "BackupStatus": "Incomplete",
    "BackupStopTime": "2018-08-13T16:19:10",
    "BackupWindow": "180",
    "CreateHardlinksStartTime": "2018-08-13T16:11:12",
    "CreateHardlinksStopTime": "2018-08-13T16:14:39",
    "DestinationEfsId": "fs-387c3591",
    "DestinationEfsSize": 54811144192,
    "DestinationPerformanceMode": "maxIO",
    "EC2Logs": "https://s3.amazonaws.com/nexus-efs-backup-efslogbucket-1uwzom8ipy8y0/ec2-logs/efs-backup-backup-20180813-1619.log",
    "ExpireItem": "1541952496",
    "InstanceType": "c5.xlarge",
    "IntervalTag": "daily",
    "Message": "The EFS backup was incomplete. The backup window expired before the full backup was completed.",
    "NumberOfFiles": 41948,
    "NumberOfFilesTransferred": 1785,
    "RemoveSnapshotStartTime": "2018-08-13T16:10:16",
    "RemoveSnapshotStopTime": "2018-08-13T16:11:12",
    "RetainPeriod": "7",
    "S3BucketSize": 7380943,
    "SourceBurstCreditBalance": 2308974418330,
    "SourceBurstCreditBalancePostBackup": 2308974418330,
    "SourceEfsId": "fs-35aae49c",
    "SourceEfsSize": 59084480512,
    "SourcePerformanceMode": "generalPurpose",
    "SourcePermittedThroughput": 104857600,
    "TotalFileSize": 60585862733,
    "TotalTransferredFileSize": 8997712481
}
```
I have the backup window set to 6 hours, although the scripts only run for a couple minutes, which seems to contradict the error message.

SSM stderr:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    10  100    10    0     0  16835      0 --:--:-- --:--:-- --:--:-- 10000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    19  100    19    0     0  35514      0 --:--:-- --:--:-- --:--:-- 19000
kill: sending signal to 15243 failed: No such process
```
SSM stdout:
```
-- 2018-08-13T16:19:08 -- uploading cloud init logs
Completed 75.6 KiB/75.6 KiB (196.1 KiB/s) with 1 file(s) remaining
upload: var/log/cloud-init-output.log to s3://nexus-efs-backup-efslogbucket-1uwzom8ipy8y0/ec2-logs/efs-backup-backup-20180813-1619.log
-- 2018-08-13T16:19:09 -- upload ec2 cloud init logs to S3, status: 0
-- 2018-08-13T16:19:09 -- uploading backup (fpsync) logs
Completed 256.0 KiB/314.1 KiB (689.4 KiB/s) with 1 file(s) remaining
Completed 314.1 KiB/314.1 KiB (745.1 KiB/s) with 1 file(s) remaining
upload: tmp/efs-backup.log to s3://nexus-efs-backup-efslogbucket-1uwzom8ipy8y0/efs-backup-logs/efs-backup-backup-fpsync-20180813-1619.log
-- 2018-08-13T16:19:10 -- upload backup fpsync logs to S3 status: 0
-- 2018-08-13T16:19:10 -- uploading backup (rsync delete) logs
Completed 139 Bytes/139 Bytes (367 Bytes/s) with 1 file(s) remaining
upload: tmp/efs-backup-rsync.log to s3://nexus-efs-backup-efslogbucket-1uwzom8ipy8y0/efs-backup-logs/efs-backup-backup-rsync-delete-20180813-1619.log
-- 2018-08-13T16:19:10 -- upload rsync delete logs to S3 status: 0
-- 2018-08-13T16:19:10 -- fpsync foreground process-id: 15243
-- 2018-08-13T16:19:10 -- kill with SIGTERM, status: 0
-- 2018-08-13T16:19:10 -- exiting loop
-- 2018-08-13T16:19:10 -- Number of files: 41948
-- 2018-08-13T16:19:10 -- Number of files transferred: 1785
-- 2018-08-13T16:19:10 -- Total file size: 60585862733
-- 2018-08-13T16:19:10 -- Total transferred file size: 8997712481
-- 2018-08-13T16:19:10 -- source efs BurstCreditBalance after backup: 2.30897441833e+12
fpsyncStatus: 1
rsync delete status: 0
-- 2018-08-13T16:19:10 -- backup finish time: 2018-08-13T16:19:10
-- 2018-08-13T16:19:10 -- backup incomplete (id: 9d74c8a7)
-- 2018-08-13T16:19:11 -- dynamo db update status: 0
-- 2018-08-13T16:19:11 -- updating lifecycle hook
-- 2018-08-13T16:19:11 -- lifecycle hook update status: 0
```
[efs-backup-backup-20180813-1619.log](https://github.com/awslabs/efs-backup/files/2283961/efs-backup-backup-20180813-1619.log)

EC2 log attached. Any advice or tips would be much appreciated, thanks!
